spring:
  application:
    name: configserver

eureka:
  client:
    enabled: false

encrypt:
  failOnError: false
  keyStore:
    location: classpath:keystore.jks
    password: ${KEYSTORE_PASSWORD:foobar} # don't use a default in production
    alias: test